In [251]:
import pandas as pd
import numpy as np

In [252]:
fernanda_df = pd.read_csv('teste2.csv')
fernanda_df.head()

,overlap_predict_proba_0_predict_proba_1,omv_pth_drift_flag,distance_class_1,distance_class_0,u_detect_drift_flag,psi_date,psi_day,psi_period,psi_nswprice,psi_nswdemand,...,dc_drift_flag,precision,recall,f1-score,kappa,last_precision,last_recall,last_f1-score,last_kappa,predicted
0,0.327752,0,0.088369,0.115614,1,5.470640,2.458795,0.006230,1.451425,0.557052,...,1,0.770,0.770,0.770,0.418605,NaN,NaN,NaN,NaN,0.471888
1,0.112416,0,0.125507,0.140794,0,6.245532,0.322755,0.005956,2.570355,0.453752,...,1,0.680,0.680,0.680,0.161426,NaN,NaN,NaN,NaN,0.217084
2,0.128616,0,0.328351,0.145538,0,6.245532,0.394768,0.004251,2.333240,0.231204,...,1,0.675,0.675,0.675,0.196141,NaN,NaN,NaN,NaN,0.183281
3,0.019308,0,0.042487,0.174229,1,6.245532,1.196824,0.005015,2.521835,0.080947,...,1,0.590,0.590,0.590,0.106851,NaN,NaN,NaN,NaN,0.113652
4,0.050605,0,0.385158,0.269707,0,6.245532,2.258510,0.004542,2.907298,0.045565,...,1,0.580,0.580,0.580,0.137488,NaN,NaN,NaN,NaN,0.140359

In [253]:
hernrique_df = pd.read_csv('teste.csv')
hernrique_df.head()

,max_date,max_day,max_period,max_nswprice,max_nswdemand,max_vicprice,max_vicdemand,max_transfer,max_predict_proba_0,max_predict_proba_1,...,kappa,f1-score,last_recall,last_precision,last_kappa,last_f1-score,meta_predict_recall,meta_predict_precision,meta_predict_kappa,meta_predict_f1-score
0,0.005044,4.0,1.0,0.166777,0.780422,0.003467,0.422915,0.414912,1.0,0.99,...,0.356334,0.750,NaN,NaN,NaN,NaN,0.754878,0.754878,0.402936,0.754878
1,0.005088,5.0,1.0,0.104750,0.740702,0.003467,0.422915,0.414912,1.0,0.78,...,0.093817,0.660,NaN,NaN,NaN,NaN,0.679944,0.679944,0.148024,0.679944
2,0.005133,6.0,1.0,0.119731,0.740405,0.003467,0.422915,0.414912,1.0,0.99,...,0.137284,0.655,NaN,NaN,NaN,NaN,0.640910,0.640910,0.144715,0.640910
3,0.005133,6.0,1.0,0.119731,0.740405,0.003467,0.422915,0.414912,1.0,0.99,...,0.083270,0.580,NaN,NaN,NaN,NaN,0.597606,0.597606,0.095232,0.597606
4,0.005177,6.0,1.0,0.119731,0.694287,0.003467,0.422915,0.414912,1.0,0.99,...,0.148019,0.585,NaN,NaN,NaN,NaN,0.602884,0.602884,0.148639,0.602884

In [254]:
print(fernanda_df.columns)

Index(['overlap_predict_proba_0_predict_proba_1', 'omv_pth_drift_flag',
       'distance_class_1', 'distance_class_0', 'u_detect_drift_flag',
       'psi_date', 'psi_day', 'psi_period', 'psi_nswprice', 'psi_nswdemand',
       ...
       'dc_drift_flag', 'precision', 'recall', 'f1-score', 'kappa',
       'last_precision', 'last_recall', 'last_f1-score', 'last_kappa',
       'predicted'],
      dtype='object', length=225)

In [255]:
print(hernrique_df.columns)

Index(['max_date', 'max_day', 'max_period', 'max_nswprice', 'max_nswdemand',
       'max_vicprice', 'max_vicdemand', 'max_transfer', 'max_predict_proba_0',
       'max_predict_proba_1',
       ...
       'kappa', 'f1-score', 'last_recall', 'last_precision', 'last_kappa',
       'last_f1-score', 'meta_predict_recall', 'meta_predict_precision',
       'meta_predict_kappa', 'meta_predict_f1-score'],
      dtype='object', length=275)

In [256]:
print([col for col in hernrique_df.columns if "kmeans" in col])

['kmeans_n_iter', 'kmeans_n_clusters', 'kmeans_inertia', 'kmeans_knee', 'kmeans_connectivity', 'kmeans_min_size_dist', 'kmeans_max_size_dist', 'kmeans_mean_size_dist']

In [257]:
left_join = [col for col in hernrique_df.columns if col not in fernanda_df.columns]
right_join = [col for col in fernanda_df.columns if col not in hernrique_df.columns]
inner_join =[col for col in fernanda_df.columns if col in hernrique_df.columns]

print(f"Tamanho da intersecção: {len(inner_join)}, {inner_join}")
print(f"Tamanho do right_join: {len(right_join)}, {right_join}")
print(f"Tamanho do left_join: {len(left_join)}, {left_join}")

Tamanho da intersecção: 35, ['overlap_predict_proba_0_predict_proba_1', 'omv_pth_drift_flag', 'distance_class_1', 'distance_class_0', 'u_detect_drift_flag', 'psi_date', 'psi_day', 'psi_period', 'psi_nswprice', 'psi_nswdemand', 'psi_vicprice', 'psi_vicdemand', 'psi_transfer', 'psi_predict_proba_0', 'psi_predict_proba_1', 'psi_drift_flag', 'prop_pca', 'predict_proba_0_ks_statistic', 'predict_proba_0_ks_pvalue', 'predict_proba_1_ks_statistic', 'predict_proba_1_ks_pvalue', 'sqsi_drift_flag', 'kmeans_n_iter', 'kmeans_n_clusters', 'kmeans_inertia', 'dc_accuracy', 'dc_drift_flag', 'precision', 'recall', 'f1-score', 'kappa', 'last_precision', 'last_recall', 'last_f1-score', 'last_kappa']
Tamanho do right_join: 190, ['psi_predict', 'date_mean', 'date_std', 'date_min', 'date_max', 'day_mean', 'day_std', 'day_min', 'day_max', 'period_mean', 'period_std', 'period_min', 'period_max', 'nswprice_mean', 'nswprice_std', 'nswprice_min', 'nswprice_max', 'nswdemand_mean', 'nswdemand_std', 'nswdemand_min', 'nswdemand_max', 'vicprice_mean', 'vicprice_std', 'vicprice_min', 'vicprice_max', 'vicdemand_mean', 'vicdemand_std', 'vicdemand_min', 'vicdemand_max', 'transfer_mean', 'transfer_std', 'transfer_min', 'transfer_max', 'predict_proba_0_mean', 'predict_proba_0_std', 'predict_proba_0_min', 'predict_proba_0_max', 'predict_proba_1_mean', 'predict_proba_1_std', 'predict_proba_1_min', 'predict_proba_1_max', 'predict_mean', 'predict_std', 'predict_min', 'predict_max', 'correlation_day_date', 'correlation_period_date', 'correlation_period_day', 'correlation_nswprice_date', 'correlation_nswprice_day', 'correlation_nswprice_period', 'correlation_nswdemand_date', 'correlation_nswdemand_day', 'correlation_nswdemand_period', 'correlation_nswdemand_nswprice', 'correlation_vicprice_date', 'correlation_vicprice_day', 'correlation_vicprice_period', 'correlation_vicprice_nswprice', 'correlation_vicprice_nswdemand', 'correlation_vicdemand_date', 'correlation_vicdemand_day', 'correlation_vicdemand_period', 'correlation_vicdemand_nswprice', 'correlation_vicdemand_nswdemand', 'correlation_vicdemand_vicprice', 'correlation_transfer_date', 'correlation_transfer_day', 'correlation_transfer_period', 'correlation_transfer_nswprice', 'correlation_transfer_nswdemand', 'correlation_transfer_vicprice', 'correlation_transfer_vicdemand', 'correlation_predict_proba_0_date', 'correlation_predict_proba_0_day', 'correlation_predict_proba_0_period', 'correlation_predict_proba_0_nswprice', 'correlation_predict_proba_0_nswdemand', 'correlation_predict_proba_0_vicprice', 'correlation_predict_proba_0_vicdemand', 'correlation_predict_proba_0_transfer', 'correlation_predict_proba_1_date', 'correlation_predict_proba_1_day', 'correlation_predict_proba_1_period', 'correlation_predict_proba_1_nswprice', 'correlation_predict_proba_1_nswdemand', 'correlation_predict_proba_1_vicprice', 'correlation_predict_proba_1_vicdemand', 'correlation_predict_proba_1_transfer', 'correlation_predict_proba_1_predict_proba_0', 'correlation_predict_date', 'correlation_predict_day', 'correlation_predict_period', 'correlation_predict_nswprice', 'correlation_predict_nswdemand', 'correlation_predict_vicprice', 'correlation_predict_vicdemand', 'correlation_predict_transfer', 'correlation_predict_predict_proba_0', 'correlation_predict_predict_proba_1', 'date_gmean', 'date_hmean', 'date_entropy', 'date_median', 'day_gmean', 'day_hmean', 'day_entropy', 'day_median', 'period_gmean', 'period_hmean', 'period_entropy', 'period_median', 'nswprice_gmean', 'nswprice_hmean', 'nswprice_entropy', 'nswprice_median', 'nswdemand_gmean', 'nswdemand_hmean', 'nswdemand_entropy', 'nswdemand_median', 'vicprice_gmean', 'vicprice_hmean', 'vicprice_entropy', 'vicprice_median', 'vicdemand_gmean', 'vicdemand_hmean', 'vicdemand_entropy', 'vicdemand_median', 'transfer_gmean', 'transfer_hmean', 'transfer_entropy', 'transfer_median', 'predict_proba_0_gmean', 'predict_proba_0_hmean', 'predict_proba_0_entropy', 'predict_proba_0_median', 'predict_proba_1_gmean', 'predict_proba_1_hmean', 'predict_proba_1_entropy', 'predict_proba_1_median', 'predict_gmean', 'predict_hmean', 'predict_entropy', 'predict_median', 'date_nr_outliers', 'day_nr_outliers', 'period_nr_outliers', 'nswprice_nr_outliers', 'nswdemand_nr_outliers', 'vicprice_nr_outliers', 'vicdemand_nr_outliers', 'transfer_nr_outliers', 'predict_proba_0_nr_outliers', 'predict_proba_1_nr_outliers', 'predict_nr_outliers', 'date_iqr', 'day_iqr', 'period_iqr', 'nswprice_iqr', 'nswdemand_iqr', 'vicprice_iqr', 'vicdemand_iqr', 'transfer_iqr', 'predict_proba_0_iqr', 'predict_proba_1_iqr', 'predict_iqr', 'date_uniqueness_ratio', 'day_uniqueness_ratio', 'period_uniqueness_ratio', 'nswprice_uniqueness_ratio', 'nswdemand_uniqueness_ratio', 'vicprice_uniqueness_ratio', 'vicdemand_uniqueness_ratio', 'transfer_uniqueness_ratio', 'predict_proba_0_uniqueness_ratio', 'predict_proba_1_uniqueness_ratio', 'predict_uniqueness_ratio', 'date_sparsity', 'day_sparsity', 'period_sparsity', 'nswprice_sparsity', 'nswdemand_sparsity', 'vicprice_sparsity', 'vicdemand_sparsity', 'transfer_sparsity', 'predict_proba_0_sparsity', 'predict_proba_1_sparsity', 'predict_sparsity', 'compacness', 'predicted']
Tamanho do left_join: 240, ['max_date', 'max_day', 'max_period', 'max_nswprice', 'max_nswdemand', 'max_vicprice', 'max_vicdemand', 'max_transfer', 'max_predict_proba_0', 'max_predict_proba_1', 'max_prediction', 'min_date', 'min_day', 'min_period', 'min_nswprice', 'min_nswdemand', 'min_vicprice', 'min_vicdemand', 'min_transfer', 'min_predict_proba_0', 'min_predict_proba_1', 'min_prediction', 'mean_date', 'mean_day', 'mean_period', 'mean_nswprice', 'mean_nswdemand', 'mean_vicprice', 'mean_vicdemand', 'mean_transfer', 'mean_predict_proba_0', 'mean_predict_proba_1', 'mean_prediction', 'median_date', 'median_day', 'median_period', 'median_nswprice', 'median_nswdemand', 'median_vicprice', 'median_vicdemand', 'median_transfer', 'median_predict_proba_0', 'median_predict_proba_1', 'median_prediction', 'std_date', 'std_day', 'std_period', 'std_nswprice', 'std_nswdemand', 'std_vicprice', 'std_vicdemand', 'std_transfer', 'std_predict_proba_0', 'std_predict_proba_1', 'std_prediction', 'var_date', 'var_day', 'var_period', 'var_nswprice', 'var_nswdemand', 'var_vicprice', 'var_vicdemand', 'var_transfer', 'var_predict_proba_0', 'var_predict_proba_1', 'var_prediction', 'kurtosis_date', 'kurtosis_day', 'kurtosis_period', 'kurtosis_nswprice', 'kurtosis_nswdemand', 'kurtosis_vicprice', 'kurtosis_vicdemand', 'kurtosis_transfer', 'kurtosis_predict_proba_0', 'kurtosis_predict_proba_1', 'kurtosis_prediction', 'skewness_date', 'skewness_day', 'skewness_period', 'skewness_nswprice', 'skewness_nswdemand', 'skewness_vicprice', 'skewness_vicdemand', 'skewness_transfer', 'skewness_predict_proba_0', 'skewness_predict_proba_1', 'skewness_prediction', 'corr_day_date', 'corr_period_date', 'corr_period_day', 'corr_nswprice_date', 'corr_nswprice_day', 'corr_nswprice_period', 'corr_nswdemand_date', 'corr_nswdemand_day', 'corr_nswdemand_period', 'corr_nswdemand_nswprice', 'corr_vicprice_date', 'corr_vicprice_day', 'corr_vicprice_period', 'corr_vicprice_nswprice', 'corr_vicprice_nswdemand', 'corr_vicdemand_date', 'corr_vicdemand_day', 'corr_vicdemand_period', 'corr_vicdemand_nswprice', 'corr_vicdemand_nswdemand', 'corr_vicdemand_vicprice', 'corr_transfer_date', 'corr_transfer_day', 'corr_transfer_period', 'corr_transfer_nswprice', 'corr_transfer_nswdemand', 'corr_transfer_vicprice', 'corr_transfer_vicdemand', 'corr_predict_proba_0_date', 'corr_predict_proba_0_day', 'corr_predict_proba_0_period', 'corr_predict_proba_0_nswprice', 'corr_predict_proba_0_nswdemand', 'corr_predict_proba_0_vicprice', 'corr_predict_proba_0_vicdemand', 'corr_predict_proba_0_transfer', 'corr_predict_proba_1_date', 'corr_predict_proba_1_day', 'corr_predict_proba_1_period', 'corr_predict_proba_1_nswprice', 'corr_predict_proba_1_nswdemand', 'corr_predict_proba_1_vicprice', 'corr_predict_proba_1_vicdemand', 'corr_predict_proba_1_transfer', 'corr_predict_proba_1_predict_proba_0', 'corr_prediction_date', 'corr_prediction_day', 'corr_prediction_period', 'corr_prediction_nswprice', 'corr_prediction_nswdemand', 'corr_prediction_vicprice', 'corr_prediction_vicdemand', 'corr_prediction_transfer', 'corr_prediction_predict_proba_0', 'corr_prediction_predict_proba_1', 'nrCorAttr', 'gmean_date', 'gmean_day', 'gmean_period', 'gmean_nswprice', 'gmean_nswdemand', 'gmean_vicprice', 'gmean_vicdemand', 'gmean_transfer', 'gmean_predict_proba_0', 'gmean_predict_proba_1', 'gmean_prediction', 'hmean_date', 'hmean_day', 'hmean_period', 'hmean_nswprice', 'hmean_nswdemand', 'hmean_vicprice', 'hmean_vicdemand', 'hmean_transfer', 'hmean_predict_proba_0', 'hmean_predict_proba_1', 'hmean_prediction', 'entropy_date', 'entropy_day', 'entropy_period', 'entropy_nswprice', 'entropy_nswdemand', 'entropy_vicprice', 'entropy_vicdemand', 'entropy_transfer', 'entropy_predict_proba_0', 'entropy_predict_proba_1', 'entropy_prediction', 'nr_outliers_date', 'nr_outliers_day', 'nr_outliers_period', 'nr_outliers_nswprice', 'nr_outliers_nswdemand', 'nr_outliers_vicprice', 'nr_outliers_vicdemand', 'nr_outliers_transfer', 'nr_outliers_predict_proba_0', 'nr_outliers_predict_proba_1', 'nr_outliers_prediction', 'iqr_date', 'iqr_day', 'iqr_period', 'iqr_nswprice', 'iqr_nswdemand', 'iqr_vicprice', 'iqr_vicdemand', 'iqr_transfer', 'iqr_predict_proba_0', 'iqr_predict_proba_1', 'iqr_prediction', 'uniqueness_ratio_date', 'uniqueness_ratio_day', 'uniqueness_ratio_period', 'uniqueness_ratio_nswprice', 'uniqueness_ratio_nswdemand', 'uniqueness_ratio_vicprice', 'uniqueness_ratio_vicdemand', 'uniqueness_ratio_transfer', 'uniqueness_ratio_predict_proba_0', 'uniqueness_ratio_predict_proba_1', 'uniqueness_ratio_prediction', 'sparsity_date', 'sparsity_day', 'sparsity_period', 'sparsity_nswprice', 'sparsity_nswdemand', 'sparsity_vicprice', 'sparsity_vicdemand', 'sparsity_transfer', 'sparsity_predict_proba_0', 'sparsity_predict_proba_1', 'sparsity_prediction', 'attr_sparsity_', 'dbscan_n_clusters', 'dbscan_noise_proportion', 'dbscan_compactness', 'dbscan_connectivity', 'dbscan_min_size_dist', 'dbscan_max_size_dist', 'dbscan_mean_size_dist', 'kmeans_knee', 'kmenas_compactness', 'kmeans_connectivity', 'kmeans_min_size_dist', 'kmeans_max_size_dist', 'kmeans_mean_size_dist', 'psi_prediction', 'meta_predict_recall', 'meta_predict_precision', 'meta_predict_kappa', 'meta_predict_f1-score']

Conseguimos peceber que eu usei o nome das métricas no prefixo enquanto a Fernanda usou no prefixo

In [258]:
metrics_name = ["max",
                "min",
                "mean",
                "median",
                "std",
                "var",
                "kurtois",
                "skewness",
                "attr_sparsity",
                "gmean",
                "hmean",
                "entropy",
                "prop_pca",
                "sparsity",
                "attr_sparsity",
                "iqr",
                "corr",
                "nrCorrAttr",
                "dbscan",
                "kmeans"
                
                ]

In [259]:
right_join = [

      f"{parts[-1]}_{'_'.join(parts[:-1])}" if (parts := column_name.split('_')) and parts[-1] in metrics_name else column_name for column_name in right_join
]
right_join

['psi_predict',
 'mean_date',
 'std_date',
 'min_date',
 'max_date',
 'mean_day',
 'std_day',
 'min_day',
 'max_day',
 'mean_period',
 'std_period',
 'min_period',
 'max_period',
 'mean_nswprice',
 'std_nswprice',
 'min_nswprice',
 'max_nswprice',
 'mean_nswdemand',
 'std_nswdemand',
 'min_nswdemand',
 'max_nswdemand',
 'mean_vicprice',
 'std_vicprice',
 'min_vicprice',
 'max_vicprice',
 'mean_vicdemand',
 'std_vicdemand',
 'min_vicdemand',
 'max_vicdemand',
 'mean_transfer',
 'std_transfer',
 'min_transfer',
 'max_transfer',
 'mean_predict_proba_0',
 'std_predict_proba_0',
 'min_predict_proba_0',
 'max_predict_proba_0',
 'mean_predict_proba_1',
 'std_predict_proba_1',
 'min_predict_proba_1',
 'max_predict_proba_1',
 'mean_predict',
 'std_predict',
 'min_predict',
 'max_predict',
 'correlation_day_date',
 'correlation_period_date',
 'correlation_period_day',
 'correlation_nswprice_date',
 'correlation_nswprice_day',
 'correlation_nswprice_period',
 'correlation_nswdemand_date',
 'correlation_nswdemand_day',
 'correlation_nswdemand_period',
 'correlation_nswdemand_nswprice',
 'correlation_vicprice_date',
 'correlation_vicprice_day',
 'correlation_vicprice_period',
 'correlation_vicprice_nswprice',
 'correlation_vicprice_nswdemand',
 'correlation_vicdemand_date',
 'correlation_vicdemand_day',
 'correlation_vicdemand_period',
 'correlation_vicdemand_nswprice',
 'correlation_vicdemand_nswdemand',
 'correlation_vicdemand_vicprice',
 'correlation_transfer_date',
 'correlation_transfer_day',
 'correlation_transfer_period',
 'correlation_transfer_nswprice',
 'correlation_transfer_nswdemand',
 'correlation_transfer_vicprice',
 'correlation_transfer_vicdemand',
 'correlation_predict_proba_0_date',
 'correlation_predict_proba_0_day',
 'correlation_predict_proba_0_period',
 'correlation_predict_proba_0_nswprice',
 'correlation_predict_proba_0_nswdemand',
 'correlation_predict_proba_0_vicprice',
 'correlation_predict_proba_0_vicdemand',
 'correlation_predict_proba_0_transfer',
 'correlation_predict_proba_1_date',
 'correlation_predict_proba_1_day',
 'correlation_predict_proba_1_period',
 'correlation_predict_proba_1_nswprice',
 'correlation_predict_proba_1_nswdemand',
 'correlation_predict_proba_1_vicprice',
 'correlation_predict_proba_1_vicdemand',
 'correlation_predict_proba_1_transfer',
 'correlation_predict_proba_1_predict_proba_0',
 'correlation_predict_date',
 'correlation_predict_day',
 'correlation_predict_period',
 'correlation_predict_nswprice',
 'correlation_predict_nswdemand',
 'correlation_predict_vicprice',
 'correlation_predict_vicdemand',
 'correlation_predict_transfer',
 'correlation_predict_predict_proba_0',
 'correlation_predict_predict_proba_1',
 'gmean_date',
 'hmean_date',
 'entropy_date',
 'median_date',
 'gmean_day',
 'hmean_day',
 'entropy_day',
 'median_day',
 'gmean_period',
 'hmean_period',
 'entropy_period',
 'median_period',
 'gmean_nswprice',
 'hmean_nswprice',
 'entropy_nswprice',
 'median_nswprice',
 'gmean_nswdemand',
 'hmean_nswdemand',
 'entropy_nswdemand',
 'median_nswdemand',
 'gmean_vicprice',
 'hmean_vicprice',
 'entropy_vicprice',
 'median_vicprice',
 'gmean_vicdemand',
 'hmean_vicdemand',
 'entropy_vicdemand',
 'median_vicdemand',
 'gmean_transfer',
 'hmean_transfer',
 'entropy_transfer',
 'median_transfer',
 'gmean_predict_proba_0',
 'hmean_predict_proba_0',
 'entropy_predict_proba_0',
 'median_predict_proba_0',
 'gmean_predict_proba_1',
 'hmean_predict_proba_1',
 'entropy_predict_proba_1',
 'median_predict_proba_1',
 'gmean_predict',
 'hmean_predict',
 'entropy_predict',
 'median_predict',
 'date_nr_outliers',
 'day_nr_outliers',
 'period_nr_outliers',
 'nswprice_nr_outliers',
 'nswdemand_nr_outliers',
 'vicprice_nr_outliers',
 'vicdemand_nr_outliers',
 'transfer_nr_outliers',
 'predict_proba_0_nr_outliers',
 'predict_proba_1_nr_outliers',
 'predict_nr_outliers',
 'iqr_date',
 'iqr_day',
 'iqr_period',
 'iqr_nswprice',
 'iqr_nswdemand',
 'iqr_vicprice',
 'iqr_vicdemand',
 'iqr_transfer',
 'iqr_predict_proba_0',
 'iqr_predict_proba_1',
 'iqr_predict',
 'date_uniqueness_ratio',
 'day_uniqueness_ratio',
 'period_uniqueness_ratio',
 'nswprice_uniqueness_ratio',
 'nswdemand_uniqueness_ratio',
 'vicprice_uniqueness_ratio',
 'vicdemand_uniqueness_ratio',
 'transfer_uniqueness_ratio',
 'predict_proba_0_uniqueness_ratio',
 'predict_proba_1_uniqueness_ratio',
 'predict_uniqueness_ratio',
 'sparsity_date',
 'sparsity_day',
 'sparsity_period',
 'sparsity_nswprice',
 'sparsity_nswdemand',
 'sparsity_vicprice',
 'sparsity_vicdemand',
 'sparsity_transfer',
 'sparsity_predict_proba_0',
 'sparsity_predict_proba_1',
 'sparsity_predict',
 'compacness',
 'predicted']

In [260]:
right_join = [col for col in right_join if col not in hernrique_df.columns]
print(f"Tamanho do right_join: {len(right_join)}, {right_join}")

Tamanho do right_join: 90, ['psi_predict', 'mean_predict', 'std_predict', 'min_predict', 'max_predict', 'correlation_day_date', 'correlation_period_date', 'correlation_period_day', 'correlation_nswprice_date', 'correlation_nswprice_day', 'correlation_nswprice_period', 'correlation_nswdemand_date', 'correlation_nswdemand_day', 'correlation_nswdemand_period', 'correlation_nswdemand_nswprice', 'correlation_vicprice_date', 'correlation_vicprice_day', 'correlation_vicprice_period', 'correlation_vicprice_nswprice', 'correlation_vicprice_nswdemand', 'correlation_vicdemand_date', 'correlation_vicdemand_day', 'correlation_vicdemand_period', 'correlation_vicdemand_nswprice', 'correlation_vicdemand_nswdemand', 'correlation_vicdemand_vicprice', 'correlation_transfer_date', 'correlation_transfer_day', 'correlation_transfer_period', 'correlation_transfer_nswprice', 'correlation_transfer_nswdemand', 'correlation_transfer_vicprice', 'correlation_transfer_vicdemand', 'correlation_predict_proba_0_date', 'correlation_predict_proba_0_day', 'correlation_predict_proba_0_period', 'correlation_predict_proba_0_nswprice', 'correlation_predict_proba_0_nswdemand', 'correlation_predict_proba_0_vicprice', 'correlation_predict_proba_0_vicdemand', 'correlation_predict_proba_0_transfer', 'correlation_predict_proba_1_date', 'correlation_predict_proba_1_day', 'correlation_predict_proba_1_period', 'correlation_predict_proba_1_nswprice', 'correlation_predict_proba_1_nswdemand', 'correlation_predict_proba_1_vicprice', 'correlation_predict_proba_1_vicdemand', 'correlation_predict_proba_1_transfer', 'correlation_predict_proba_1_predict_proba_0', 'correlation_predict_date', 'correlation_predict_day', 'correlation_predict_period', 'correlation_predict_nswprice', 'correlation_predict_nswdemand', 'correlation_predict_vicprice', 'correlation_predict_vicdemand', 'correlation_predict_transfer', 'correlation_predict_predict_proba_0', 'correlation_predict_predict_proba_1', 'gmean_predict', 'hmean_predict', 'entropy_predict', 'median_predict', 'date_nr_outliers', 'day_nr_outliers', 'period_nr_outliers', 'nswprice_nr_outliers', 'nswdemand_nr_outliers', 'vicprice_nr_outliers', 'vicdemand_nr_outliers', 'transfer_nr_outliers', 'predict_proba_0_nr_outliers', 'predict_proba_1_nr_outliers', 'predict_nr_outliers', 'iqr_predict', 'date_uniqueness_ratio', 'day_uniqueness_ratio', 'period_uniqueness_ratio', 'nswprice_uniqueness_ratio', 'nswdemand_uniqueness_ratio', 'vicprice_uniqueness_ratio', 'vicdemand_uniqueness_ratio', 'transfer_uniqueness_ratio', 'predict_proba_0_uniqueness_ratio', 'predict_proba_1_uniqueness_ratio', 'predict_uniqueness_ratio', 'sparsity_predict', 'compacness', 'predicted']

Correlation no meu caso é corr...

In [261]:
right_join = [ f"corr{item[11:]}" if item.startswith('correlation') else item for item in right_join]
right_join

['psi_predict',
 'mean_predict',
 'std_predict',
 'min_predict',
 'max_predict',
 'corr_day_date',
 'corr_period_date',
 'corr_period_day',
 'corr_nswprice_date',
 'corr_nswprice_day',
 'corr_nswprice_period',
 'corr_nswdemand_date',
 'corr_nswdemand_day',
 'corr_nswdemand_period',
 'corr_nswdemand_nswprice',
 'corr_vicprice_date',
 'corr_vicprice_day',
 'corr_vicprice_period',
 'corr_vicprice_nswprice',
 'corr_vicprice_nswdemand',
 'corr_vicdemand_date',
 'corr_vicdemand_day',
 'corr_vicdemand_period',
 'corr_vicdemand_nswprice',
 'corr_vicdemand_nswdemand',
 'corr_vicdemand_vicprice',
 'corr_transfer_date',
 'corr_transfer_day',
 'corr_transfer_period',
 'corr_transfer_nswprice',
 'corr_transfer_nswdemand',
 'corr_transfer_vicprice',
 'corr_transfer_vicdemand',
 'corr_predict_proba_0_date',
 'corr_predict_proba_0_day',
 'corr_predict_proba_0_period',
 'corr_predict_proba_0_nswprice',
 'corr_predict_proba_0_nswdemand',
 'corr_predict_proba_0_vicprice',
 'corr_predict_proba_0_vicdemand',
 'corr_predict_proba_0_transfer',
 'corr_predict_proba_1_date',
 'corr_predict_proba_1_day',
 'corr_predict_proba_1_period',
 'corr_predict_proba_1_nswprice',
 'corr_predict_proba_1_nswdemand',
 'corr_predict_proba_1_vicprice',
 'corr_predict_proba_1_vicdemand',
 'corr_predict_proba_1_transfer',
 'corr_predict_proba_1_predict_proba_0',
 'corr_predict_date',
 'corr_predict_day',
 'corr_predict_period',
 'corr_predict_nswprice',
 'corr_predict_nswdemand',
 'corr_predict_vicprice',
 'corr_predict_vicdemand',
 'corr_predict_transfer',
 'corr_predict_predict_proba_0',
 'corr_predict_predict_proba_1',
 'gmean_predict',
 'hmean_predict',
 'entropy_predict',
 'median_predict',
 'date_nr_outliers',
 'day_nr_outliers',
 'period_nr_outliers',
 'nswprice_nr_outliers',
 'nswdemand_nr_outliers',
 'vicprice_nr_outliers',
 'vicdemand_nr_outliers',
 'transfer_nr_outliers',
 'predict_proba_0_nr_outliers',
 'predict_proba_1_nr_outliers',
 'predict_nr_outliers',
 'iqr_predict',
 'date_uniqueness_ratio',
 'day_uniqueness_ratio',
 'period_uniqueness_ratio',
 'nswprice_uniqueness_ratio',
 'nswdemand_uniqueness_ratio',
 'vicprice_uniqueness_ratio',
 'vicdemand_uniqueness_ratio',
 'transfer_uniqueness_ratio',
 'predict_proba_0_uniqueness_ratio',
 'predict_proba_1_uniqueness_ratio',
 'predict_uniqueness_ratio',
 'sparsity_predict',
 'compacness',
 'predicted']

In [262]:
right_join = [col for col in right_join if col not in hernrique_df.columns]
print(f"Tamanho do right_join: {len(right_join)}, {right_join}")

Tamanho do right_join: 45, ['psi_predict', 'mean_predict', 'std_predict', 'min_predict', 'max_predict', 'corr_predict_date', 'corr_predict_day', 'corr_predict_period', 'corr_predict_nswprice', 'corr_predict_nswdemand', 'corr_predict_vicprice', 'corr_predict_vicdemand', 'corr_predict_transfer', 'corr_predict_predict_proba_0', 'corr_predict_predict_proba_1', 'gmean_predict', 'hmean_predict', 'entropy_predict', 'median_predict', 'date_nr_outliers', 'day_nr_outliers', 'period_nr_outliers', 'nswprice_nr_outliers', 'nswdemand_nr_outliers', 'vicprice_nr_outliers', 'vicdemand_nr_outliers', 'transfer_nr_outliers', 'predict_proba_0_nr_outliers', 'predict_proba_1_nr_outliers', 'predict_nr_outliers', 'iqr_predict', 'date_uniqueness_ratio', 'day_uniqueness_ratio', 'period_uniqueness_ratio', 'nswprice_uniqueness_ratio', 'nswdemand_uniqueness_ratio', 'vicprice_uniqueness_ratio', 'vicdemand_uniqueness_ratio', 'transfer_uniqueness_ratio', 'predict_proba_0_uniqueness_ratio', 'predict_proba_1_uniqueness_ratio', 'predict_uniqueness_ratio', 'sparsity_predict', 'compacness', 'predicted']

<li>Fernanda chama de predict, eu chamo de prediction</li>
<li>uniqueness_ratio_ e nr_outliers ficaram de fora da conversão</li>
<li>kmeans intertia e kmenas n_clusters</li>
<li>compacness -> compactness</li>


DESCOBRI QUE NÃO ESTAVA COMPUTANDO OS KMEANS :D

In [263]:
right_join = [col for col in right_join if not "predict" in col]
print(f"Tamanho do right_join: {len(right_join)}, {right_join}")

Tamanho do right_join: 17, ['date_nr_outliers', 'day_nr_outliers', 'period_nr_outliers', 'nswprice_nr_outliers', 'nswdemand_nr_outliers', 'vicprice_nr_outliers', 'vicdemand_nr_outliers', 'transfer_nr_outliers', 'date_uniqueness_ratio', 'day_uniqueness_ratio', 'period_uniqueness_ratio', 'nswprice_uniqueness_ratio', 'nswdemand_uniqueness_ratio', 'vicprice_uniqueness_ratio', 'vicdemand_uniqueness_ratio', 'transfer_uniqueness_ratio', 'compacness']

In [264]:
print(len("nr_outliers"))
print(len("uniqueness_ratio"))

11
16

In [265]:
right_join = [ f"uniqueness_ratio_{item[:-17]}" if item.endswith('uniqueness_ratio') else item for item in right_join]
right_join

['date_nr_outliers',
 'day_nr_outliers',
 'period_nr_outliers',
 'nswprice_nr_outliers',
 'nswdemand_nr_outliers',
 'vicprice_nr_outliers',
 'vicdemand_nr_outliers',
 'transfer_nr_outliers',
 'uniqueness_ratio_date',
 'uniqueness_ratio_day',
 'uniqueness_ratio_period',
 'uniqueness_ratio_nswprice',
 'uniqueness_ratio_nswdemand',
 'uniqueness_ratio_vicprice',
 'uniqueness_ratio_vicdemand',
 'uniqueness_ratio_transfer',
 'compacness']

In [266]:
right_join = [ f"nr_outliers_{item[:-12]}" if item.endswith('nr_outliers') else item for item in right_join]
right_join

['nr_outliers_date',
 'nr_outliers_day',
 'nr_outliers_period',
 'nr_outliers_nswprice',
 'nr_outliers_nswdemand',
 'nr_outliers_vicprice',
 'nr_outliers_vicdemand',
 'nr_outliers_transfer',
 'uniqueness_ratio_date',
 'uniqueness_ratio_day',
 'uniqueness_ratio_period',
 'uniqueness_ratio_nswprice',
 'uniqueness_ratio_nswdemand',
 'uniqueness_ratio_vicprice',
 'uniqueness_ratio_vicdemand',
 'uniqueness_ratio_transfer',
 'compacness']

In [267]:
right_join = [col  for col in right_join if col not in hernrique_df.columns]
right_join

['compacness']

F1-score são métricas targer e basline, tá tranquilo :D
Temos um guia de como converter as colunas de uma tabela em outra

In [268]:

def transform_columns(name:str):
    parts = name.split("_")
    if(parts[-1] in metrics_name):
        name = f"{parts[-1]}_{'_'.join(parts[:-1])}"
    
    if(name.endswith("nr_outliers")):
        name = f"nr_outliers_{name[:-12]}"
    
    if(name.endswith("uniqueness_ratio")):
         name = f"uniqueness_ratio_{name[:-17]}"
    
    if(name=="compacness"):
        return "compactness"
    
    if("predict" in name):
        name = name.replace("predict","prediction")
    
    if(name.startswith('correlation')):
        name= f"corr{name[11:]}"
    return name

In [269]:

fernanda_df.rename(columns=transform_columns,inplace=True)

In [270]:
left_join = [col for col in hernrique_df.columns if col not in fernanda_df.columns]
right_join = [col for col in fernanda_df.columns if col not in hernrique_df.columns]
inner_join =[col for col in fernanda_df.columns if col in hernrique_df.columns]

print(f"Tamanho da intersecção: {len(inner_join)}, {inner_join}")
print(f"Tamanho do right_join: {len(right_join)}, {right_join}")
print(f"Tamanho do left_join: {len(left_join)}, {left_join}")

Tamanho da intersecção: 173, ['omv_pth_drift_flag', 'distance_class_1', 'distance_class_0', 'u_detect_drift_flag', 'psi_date', 'psi_day', 'psi_period', 'psi_nswprice', 'psi_nswdemand', 'psi_vicprice', 'psi_vicdemand', 'psi_transfer', 'psi_prediction', 'psi_drift_flag', 'mean_date', 'std_date', 'min_date', 'max_date', 'mean_day', 'std_day', 'min_day', 'max_day', 'mean_period', 'std_period', 'min_period', 'max_period', 'mean_nswprice', 'std_nswprice', 'min_nswprice', 'max_nswprice', 'mean_nswdemand', 'std_nswdemand', 'min_nswdemand', 'max_nswdemand', 'mean_vicprice', 'std_vicprice', 'min_vicprice', 'max_vicprice', 'mean_vicdemand', 'std_vicdemand', 'min_vicdemand', 'max_vicdemand', 'mean_transfer', 'std_transfer', 'min_transfer', 'max_transfer', 'mean_prediction', 'std_prediction', 'min_prediction', 'max_prediction', 'corr_day_date', 'corr_period_date', 'corr_period_day', 'corr_nswprice_date', 'corr_nswprice_day', 'corr_nswprice_period', 'corr_nswdemand_date', 'corr_nswdemand_day', 'corr_nswdemand_period', 'corr_nswdemand_nswprice', 'corr_vicprice_date', 'corr_vicprice_day', 'corr_vicprice_period', 'corr_vicprice_nswprice', 'corr_vicprice_nswdemand', 'corr_vicdemand_date', 'corr_vicdemand_day', 'corr_vicdemand_period', 'corr_vicdemand_nswprice', 'corr_vicdemand_nswdemand', 'corr_vicdemand_vicprice', 'corr_transfer_date', 'corr_transfer_day', 'corr_transfer_period', 'corr_transfer_nswprice', 'corr_transfer_nswdemand', 'corr_transfer_vicprice', 'corr_transfer_vicdemand', 'corr_prediction_date', 'corr_prediction_day', 'corr_prediction_period', 'corr_prediction_nswprice', 'corr_prediction_nswdemand', 'corr_prediction_vicprice', 'corr_prediction_vicdemand', 'corr_prediction_transfer', 'gmean_date', 'hmean_date', 'entropy_date', 'median_date', 'gmean_day', 'hmean_day', 'entropy_day', 'median_day', 'gmean_period', 'hmean_period', 'entropy_period', 'median_period', 'gmean_nswprice', 'hmean_nswprice', 'entropy_nswprice', 'median_nswprice', 'gmean_nswdemand', 'hmean_nswdemand', 'entropy_nswdemand', 'median_nswdemand', 'gmean_vicprice', 'hmean_vicprice', 'entropy_vicprice', 'median_vicprice', 'gmean_vicdemand', 'hmean_vicdemand', 'entropy_vicdemand', 'median_vicdemand', 'gmean_transfer', 'hmean_transfer', 'entropy_transfer', 'median_transfer', 'gmean_prediction', 'hmean_prediction', 'entropy_prediction', 'median_prediction', 'nr_outliers_date', 'nr_outliers_day', 'nr_outliers_period', 'nr_outliers_nswprice', 'nr_outliers_nswdemand', 'nr_outliers_vicprice', 'nr_outliers_vicdemand', 'nr_outliers_transfer', 'nr_outliers_prediction', 'iqr_date', 'iqr_day', 'iqr_period', 'iqr_nswprice', 'iqr_nswdemand', 'iqr_vicprice', 'iqr_vicdemand', 'iqr_transfer', 'iqr_prediction', 'uniqueness_ratio_date', 'uniqueness_ratio_day', 'uniqueness_ratio_period', 'uniqueness_ratio_nswprice', 'uniqueness_ratio_nswdemand', 'uniqueness_ratio_vicprice', 'uniqueness_ratio_vicdemand', 'uniqueness_ratio_transfer', 'uniqueness_ratio_prediction', 'sparsity_date', 'sparsity_day', 'sparsity_period', 'sparsity_nswprice', 'sparsity_nswdemand', 'sparsity_vicprice', 'sparsity_vicdemand', 'sparsity_transfer', 'sparsity_prediction', 'prop_pca', 'sqsi_drift_flag', 'kmeans_n_iter', 'kmeans_n_clusters', 'kmeans_inertia', 'dc_accuracy', 'dc_drift_flag', 'precision', 'recall', 'f1-score', 'kappa', 'last_precision', 'last_recall', 'last_f1-score', 'last_kappa']
Tamanho do right_join: 52, ['overlap_prediction_proba_0_prediction_proba_1', 'psi_prediction_proba_0', 'psi_prediction_proba_1', 'mean_prediction_proba_0', 'std_prediction_proba_0', 'min_prediction_proba_0', 'max_prediction_proba_0', 'mean_prediction_proba_1', 'std_prediction_proba_1', 'min_prediction_proba_1', 'max_prediction_proba_1', 'corr_prediction_proba_0_date', 'corr_prediction_proba_0_day', 'corr_prediction_proba_0_period', 'corr_prediction_proba_0_nswprice', 'corr_prediction_proba_0_nswdemand', 'corr_prediction_proba_0_vicprice', 'corr_prediction_proba_0_vicdemand', 'corr_prediction_proba_0_transfer', 'corr_prediction_proba_1_date', 'corr_prediction_proba_1_day', 'corr_prediction_proba_1_period', 'corr_prediction_proba_1_nswprice', 'corr_prediction_proba_1_nswdemand', 'corr_prediction_proba_1_vicprice', 'corr_prediction_proba_1_vicdemand', 'corr_prediction_proba_1_transfer', 'corr_prediction_proba_1_prediction_proba_0', 'corr_prediction_prediction_proba_0', 'corr_prediction_prediction_proba_1', 'gmean_prediction_proba_0', 'hmean_prediction_proba_0', 'entropy_prediction_proba_0', 'median_prediction_proba_0', 'gmean_prediction_proba_1', 'hmean_prediction_proba_1', 'entropy_prediction_proba_1', 'median_prediction_proba_1', 'nr_outliers_prediction_proba_0', 'nr_outliers_prediction_proba_1', 'iqr_prediction_proba_0', 'iqr_prediction_proba_1', 'uniqueness_ratio_prediction_proba_0', 'uniqueness_ratio_prediction_proba_1', 'sparsity_prediction_proba_0', 'sparsity_prediction_proba_1', 'prediction_proba_0_ks_statistic', 'prediction_proba_0_ks_pvalue', 'prediction_proba_1_ks_statistic', 'prediction_proba_1_ks_pvalue', 'compactness', 'predictioned']
Tamanho do left_join: 102, ['max_predict_proba_0', 'max_predict_proba_1', 'min_predict_proba_0', 'min_predict_proba_1', 'mean_predict_proba_0', 'mean_predict_proba_1', 'median_predict_proba_0', 'median_predict_proba_1', 'std_predict_proba_0', 'std_predict_proba_1', 'var_date', 'var_day', 'var_period', 'var_nswprice', 'var_nswdemand', 'var_vicprice', 'var_vicdemand', 'var_transfer', 'var_predict_proba_0', 'var_predict_proba_1', 'var_prediction', 'kurtosis_date', 'kurtosis_day', 'kurtosis_period', 'kurtosis_nswprice', 'kurtosis_nswdemand', 'kurtosis_vicprice', 'kurtosis_vicdemand', 'kurtosis_transfer', 'kurtosis_predict_proba_0', 'kurtosis_predict_proba_1', 'kurtosis_prediction', 'skewness_date', 'skewness_day', 'skewness_period', 'skewness_nswprice', 'skewness_nswdemand', 'skewness_vicprice', 'skewness_vicdemand', 'skewness_transfer', 'skewness_predict_proba_0', 'skewness_predict_proba_1', 'skewness_prediction', 'corr_predict_proba_0_date', 'corr_predict_proba_0_day', 'corr_predict_proba_0_period', 'corr_predict_proba_0_nswprice', 'corr_predict_proba_0_nswdemand', 'corr_predict_proba_0_vicprice', 'corr_predict_proba_0_vicdemand', 'corr_predict_proba_0_transfer', 'corr_predict_proba_1_date', 'corr_predict_proba_1_day', 'corr_predict_proba_1_period', 'corr_predict_proba_1_nswprice', 'corr_predict_proba_1_nswdemand', 'corr_predict_proba_1_vicprice', 'corr_predict_proba_1_vicdemand', 'corr_predict_proba_1_transfer', 'corr_predict_proba_1_predict_proba_0', 'corr_prediction_predict_proba_0', 'corr_prediction_predict_proba_1', 'nrCorAttr', 'gmean_predict_proba_0', 'gmean_predict_proba_1', 'hmean_predict_proba_0', 'hmean_predict_proba_1', 'entropy_predict_proba_0', 'entropy_predict_proba_1', 'nr_outliers_predict_proba_0', 'nr_outliers_predict_proba_1', 'iqr_predict_proba_0', 'iqr_predict_proba_1', 'uniqueness_ratio_predict_proba_0', 'uniqueness_ratio_predict_proba_1', 'sparsity_predict_proba_0', 'sparsity_predict_proba_1', 'attr_sparsity_', 'dbscan_n_clusters', 'dbscan_noise_proportion', 'dbscan_compactness', 'dbscan_connectivity', 'dbscan_min_size_dist', 'dbscan_max_size_dist', 'dbscan_mean_size_dist', 'kmeans_knee', 'kmenas_compactness', 'kmeans_connectivity', 'kmeans_min_size_dist', 'kmeans_max_size_dist', 'kmeans_mean_size_dist', 'psi_predict_proba_0', 'psi_predict_proba_1', 'overlap_predict_proba_0_predict_proba_1', 'predict_proba_0_ks_statistic', 'predict_proba_0_ks_pvalue', 'predict_proba_1_ks_statistic', 'predict_proba_1_ks_pvalue', 'meta_predict_recall', 'meta_predict_precision', 'meta_predict_kappa', 'meta_predict_f1-score']

In [271]:

fernanda_df.drop(columns=right_join,inplace=True)
hernrique_df.drop(columns=left_join,inplace=True)

In [272]:
fernanda_df.sort_index(axis=1,inplace=True)
hernrique_df.sort_index(axis=1,inplace=True)

In [273]:
hernrique_df.head()

,corr_day_date,corr_nswdemand_date,corr_nswdemand_day,corr_nswdemand_nswprice,corr_nswdemand_period,corr_nswprice_date,corr_nswprice_day,corr_nswprice_period,corr_period_date,corr_period_day,...,u_detect_drift_flag,uniqueness_ratio_date,uniqueness_ratio_day,uniqueness_ratio_nswdemand,uniqueness_ratio_nswprice,uniqueness_ratio_period,uniqueness_ratio_prediction,uniqueness_ratio_transfer,uniqueness_ratio_vicdemand,uniqueness_ratio_vicprice
0,0.999988,-0.156516,-0.156608,0.154937,0.575701,-0.750205,-0.748697,0.105738,-0.249489,-0.249749,...,1,0.025,0.025,0.935,0.245,0.24,0.01,0.005,0.005,0.005
1,0.999988,-0.338975,-0.338807,0.007735,0.553609,-0.395583,-0.392474,-0.079184,-0.307159,-0.306940,...,1,0.025,0.025,0.945,0.215,0.24,0.01,0.005,0.005,0.005
2,0.999994,-0.289611,-0.289460,-0.126251,0.504232,0.187752,0.189176,-0.061091,-0.128986,-0.128025,...,0,0.030,0.030,0.955,0.220,0.24,0.01,0.005,0.005,0.005
3,0.999988,-0.536906,-0.536209,-0.076977,0.547116,0.467754,0.468800,-0.019177,-0.307159,-0.306940,...,1,0.025,0.025,0.970,0.195,0.24,0.01,0.005,0.005,0.005
4,0.142799,-0.498248,-0.043800,0.036807,0.552856,0.311112,0.297022,0.046415,-0.249489,0.197185,...,0,0.025,0.025,0.995,0.200,0.24,0.01,0.005,0.005,0.005

In [274]:
fernanda_df.head()

,corr_day_date,corr_nswdemand_date,corr_nswdemand_day,corr_nswdemand_nswprice,corr_nswdemand_period,corr_nswprice_date,corr_nswprice_day,corr_nswprice_period,corr_period_date,corr_period_day,...,u_detect_drift_flag,uniqueness_ratio_date,uniqueness_ratio_day,uniqueness_ratio_nswdemand,uniqueness_ratio_nswprice,uniqueness_ratio_period,uniqueness_ratio_prediction,uniqueness_ratio_transfer,uniqueness_ratio_vicdemand,uniqueness_ratio_vicprice
0,0.999988,-0.156516,-0.156608,0.154937,0.575701,-0.750205,-0.748697,0.105738,-0.249489,-0.249749,...,1,0.025,0.025,0.935,0.245,0.24,0.01,0.005,0.005,0.005
1,0.999988,-0.338975,-0.338807,0.007735,0.553609,-0.395583,-0.392474,-0.079184,-0.307159,-0.306940,...,0,0.025,0.025,0.945,0.215,0.24,0.01,0.005,0.005,0.005
2,0.999994,-0.289611,-0.289460,-0.126251,0.504232,0.187752,0.189176,-0.061091,-0.128986,-0.128025,...,0,0.030,0.030,0.955,0.220,0.24,0.01,0.005,0.005,0.005
3,0.999988,-0.536906,-0.536209,-0.076977,0.547116,0.467754,0.468800,-0.019177,-0.307159,-0.306940,...,1,0.025,0.025,0.970,0.195,0.24,0.01,0.005,0.005,0.005
4,0.142799,-0.498248,-0.043800,0.036807,0.552856,0.311112,0.297022,0.046415,-0.249489,0.197185,...,0,0.025,0.025,0.995,0.200,0.24,0.01,0.005,0.005,0.005

Esses valores coincidentes podem ter vindos todos da offline. É bom pegar linhas aleatórias

In [275]:
print(f"Shape da Fernanda {fernanda_df.shape}")
print(f"Shape do Henrique {hernrique_df.shape}")

Shape da Fernanda (1421, 173)
Shape do Henrique (1421, 173)

SUSPEITO

In [276]:
print(fernanda_df.shape[0]-hernrique_df.shape[0])

0

In [277]:
print(hernrique_df.iloc[1]==fernanda_df.iloc[1])
print(comp[comp == False].index.tolist())

corr_day_date                  True
corr_nswdemand_date            True
corr_nswdemand_day             True
corr_nswdemand_nswprice        True
corr_nswdemand_period          True
                               ...
uniqueness_ratio_period        True
uniqueness_ratio_prediction    True
uniqueness_ratio_transfer      True
uniqueness_ratio_vicdemand     True
uniqueness_ratio_vicprice      True
Name: 1, Length: 173, dtype: bool
[]

In [278]:
def has_diffs(pos)->bool:
    comp = hernrique_df.iloc[pos] == fernanda_df.iloc[pos]
    if(comp.all()):
         return True
    else:
        aut = comp[comp == False].index.tolist()
        print(len(aut),aut)
        return False

In [279]:
has_diffs(1)

50 ['corr_prediction_date', 'corr_prediction_day', 'corr_prediction_nswdemand', 'corr_prediction_nswprice', 'corr_prediction_period', 'corr_prediction_transfer', 'corr_prediction_vicdemand', 'corr_prediction_vicprice', 'corr_transfer_date', 'corr_transfer_day', 'corr_transfer_nswdemand', 'corr_transfer_nswprice', 'corr_transfer_period', 'corr_transfer_vicdemand', 'corr_transfer_vicprice', 'corr_vicdemand_date', 'corr_vicdemand_day', 'corr_vicdemand_nswdemand', 'corr_vicdemand_nswprice', 'corr_vicdemand_period', 'corr_vicdemand_vicprice', 'corr_vicprice_date', 'corr_vicprice_day', 'corr_vicprice_nswdemand', 'corr_vicprice_nswprice', 'corr_vicprice_period', 'distance_class_0', 'distance_class_1', 'entropy_date', 'entropy_day', 'entropy_nswprice', 'entropy_prediction', 'f1-score', 'kappa', 'kmeans_inertia', 'kmeans_n_iter', 'last_f1-score', 'last_kappa', 'last_precision', 'last_recall', 'mean_prediction', 'nr_outliers_prediction', 'precision', 'prop_pca', 'psi_prediction', 'recall', 'sparsity_period', 'sparsity_prediction', 'std_prediction', 'u_detect_drift_flag']

False

In [280]:
print(hernrique_df["entropy_nswprice"])
print(fernanda_df["entropy_nswprice"][:1378])

0       3.204361
1       3.060527
2       3.019711
3       3.029758
4       3.086617
          ...
1416    5.012293
1417    5.045251
1418    5.039672
1419    5.072631
1420    5.119452
Name: entropy_nswprice, Length: 1421, dtype: float64
0       3.204361
1       3.060527
2       3.019711
3       3.029758
4       3.086617
          ...
1373    5.093771
1374    5.086840
1375    5.105935
1376    5.058623
1377    5.109759
Name: entropy_nswprice, Length: 1378, dtype: float64

Me parece aceitável...
Os predictions com certeza estariam diferentes por que os meta modelos utilizados não têm outptuna e os hiperparametros são elevemente diferentes. Os outros parecem ter diferenças de calores aceitáveis

Por estarem parecidos os datasets até a linha que eu tenho no henrique_df, acho que deve as linhas faltantes deveriam ter vindo do final da fase online, quando eu só dou update nos targets, ou algo do tipo

In [281]:
comp =hernrique_df['uniqueness_ratio_nswprice']==fernanda_df["uniqueness_ratio_nswprice"]

print(comp)

0       True
1       True
2       True
3       True
4       True
        ...
1416    True
1417    True
1418    True
1419    True
1420    True
Name: uniqueness_ratio_nswprice, Length: 1421, dtype: bool

In [282]:
prim = comp.idxmin()
prim

0

Estamos computando algo diferente na fase online

Att: Descobri que troquei um > por um >=


Att: Os valores bateram

In [283]:
diffs = (hernrique_df - fernanda_df).abs().max()
for col, valor in diffs.sort_values(ascending=False).items():
    print(f"{col}: {valor:.6f}")

kmeans_inertia: 623.720218
nr_outliers_prediction: 50.000000
kmeans_n_iter: 24.000000
psi_prediction: 9.009764
kmeans_n_clusters: 4.000000
sqsi_drift_flag: 1.000000
max_prediction: 1.000000
omv_pth_drift_flag: 1.000000
u_detect_drift_flag: 1.000000
sparsity_prediction: 1.000000
median_prediction: 1.000000
iqr_prediction: 1.000000
corr_prediction_nswprice: 0.449535
last_kappa: 0.442110
kappa: 0.442110
corr_prediction_vicprice: 0.390033
corr_prediction_date: 0.388768
distance_class_1: 0.387220
corr_prediction_vicdemand: 0.329360
corr_prediction_transfer: 0.321616
corr_prediction_day: 0.302904
entropy_prediction: 0.302538
corr_prediction_nswdemand: 0.300387
std_prediction: 0.286900
corr_prediction_period: 0.284977
prop_pca: 0.262727
sparsity_day: 0.240000
mean_prediction: 0.225000
recall: 0.225000
precision: 0.225000
last_recall: 0.225000
f1-score: 0.225000
last_precision: 0.225000
last_f1-score: 0.225000
distance_class_0: 0.121638
sparsity_vicprice: 0.055000
sparsity_nswprice: 0.055000
sparsity_period: 0.025000
sparsity_nswdemand: 0.005000
sparsity_vicdemand: 0.005000
uniqueness_ratio_prediction: 0.005000
sparsity_transfer: 0.005000
entropy_nswprice: 0.000000
entropy_nswdemand: 0.000000
entropy_transfer: 0.000000
entropy_vicdemand: 0.000000
entropy_vicprice: 0.000000
entropy_day: 0.000000
entropy_date: 0.000000
min_prediction: 0.000000
min_transfer: 0.000000
min_vicdemand: 0.000000
min_vicprice: 0.000000
nr_outliers_date: 0.000000
corr_day_date: 0.000000
nr_outliers_nswdemand: 0.000000
min_period: 0.000000
min_nswprice: 0.000000
min_nswdemand: 0.000000
min_day: 0.000000
min_date: 0.000000
median_vicprice: 0.000000
median_vicdemand: 0.000000
median_transfer: 0.000000
median_period: 0.000000
median_nswprice: 0.000000
median_nswdemand: 0.000000
median_day: 0.000000
nr_outliers_day: 0.000000
psi_vicprice: 0.000000
nr_outliers_nswprice: 0.000000
std_day: 0.000000
uniqueness_ratio_vicdemand: 0.000000
uniqueness_ratio_transfer: 0.000000
uniqueness_ratio_period: 0.000000
uniqueness_ratio_nswprice: 0.000000
uniqueness_ratio_nswdemand: 0.000000
uniqueness_ratio_day: 0.000000
uniqueness_ratio_date: 0.000000
std_vicprice: 0.000000
std_vicdemand: 0.000000
std_transfer: 0.000000
std_period: 0.000000
std_nswprice: 0.000000
std_nswdemand: 0.000000
std_date: 0.000000
nr_outliers_period: 0.000000
sparsity_date: 0.000000
mean_vicprice: 0.000000
psi_vicdemand: 0.000000
psi_transfer: 0.000000
psi_period: 0.000000
psi_nswprice: 0.000000
psi_nswdemand: 0.000000
psi_drift_flag: 0.000000
psi_day: 0.000000
psi_date: 0.000000
nr_outliers_vicprice: 0.000000
nr_outliers_vicdemand: 0.000000
nr_outliers_transfer: 0.000000
median_date: 0.000000
max_day: 0.000000
mean_vicdemand: 0.000000
corr_vicprice_nswprice: 0.000000
corr_vicdemand_nswprice: 0.000000
corr_vicdemand_period: 0.000000
corr_vicdemand_vicprice: 0.000000
corr_vicprice_date: 0.000000
corr_vicprice_day: 0.000000
corr_vicprice_nswdemand: 0.000000
corr_vicprice_period: 0.000000
corr_vicdemand_day: 0.000000
dc_accuracy: 0.000000
dc_drift_flag: 0.000000
entropy_period: 0.000000
gmean_date: 0.000000
gmean_day: 0.000000
gmean_nswdemand: 0.000000
corr_vicdemand_nswdemand: 0.000000
corr_vicdemand_date: 0.000000
gmean_period: 0.000000
corr_period_date: 0.000000
corr_nswdemand_day: 0.000000
corr_nswdemand_nswprice: 0.000000
corr_nswdemand_period: 0.000000
corr_nswprice_date: 0.000000
corr_nswprice_day: 0.000000
corr_nswprice_period: 0.000000
corr_period_day: 0.000000
corr_transfer_vicprice: 0.000000
corr_transfer_date: 0.000000
corr_transfer_day: 0.000000
corr_transfer_nswdemand: 0.000000
corr_transfer_nswprice: 0.000000
corr_transfer_period: 0.000000
corr_transfer_vicdemand: 0.000000
gmean_nswprice: 0.000000
gmean_prediction: 0.000000
mean_transfer: 0.000000
max_transfer: 0.000000
iqr_vicprice: 0.000000
max_date: 0.000000
corr_nswdemand_date: 0.000000
max_nswdemand: 0.000000
max_nswprice: 0.000000
max_period: 0.000000
max_vicdemand: 0.000000
iqr_transfer: 0.000000
max_vicprice: 0.000000
mean_date: 0.000000
mean_day: 0.000000
mean_nswdemand: 0.000000
mean_nswprice: 0.000000
mean_period: 0.000000
iqr_vicdemand: 0.000000
iqr_period: 0.000000
gmean_transfer: 0.000000
hmean_period: 0.000000
gmean_vicdemand: 0.000000
gmean_vicprice: 0.000000
hmean_date: 0.000000
hmean_day: 0.000000
hmean_nswdemand: 0.000000
hmean_nswprice: 0.000000
hmean_prediction: 0.000000
iqr_nswprice: 0.000000
hmean_transfer: 0.000000
hmean_vicdemand: 0.000000
hmean_vicprice: 0.000000
iqr_date: 0.000000
iqr_day: 0.000000
iqr_nswdemand: 0.000000
uniqueness_ratio_vicprice: 0.000000

Diferença relevante = intertia, n_inter
Fernanda faz a normalização no kmeans, eu não